### ISSUE TITLE
Custom prefix still only one char long

### ISSUE THREAD

**Issue by VerstreuteSeele** [Sahnee-DE/sahnee-bot#25]
Hey. I actually found some time to test the bot today and even with the newest version of the bot I encountered the same error with a custom prefix as last time:

Newtonsoft.Json.JsonSerializationException: Error converting value "c!" to type 'System.Char'. Path 'General.CommandPrefix', line 6, position 33.
 ---> System.FormatException: String must be exactly one character long.

This was tested on windows. I didnt have the time to check if it might just be a windows-only error as you stated before that longer prefixes would now work. Might have some time to try it on my raspberry tomorrow, cant promise anything tho.

**Comment by VerstreuteSeele** [comment]
On a positive note, at least on windows the commands work with the default or any other 1char long prefix

**Comment by VerstreuteSeele** [comment]
Checked, prefix issue also happens on linux-arm.

**Comment by DaNeubi** [comment]
Are you sure you are building from the lastest master branch?

Because this message got removed form the code.
See: [Exact line](https://github.com/Sahnee-DE/sahnee-bot/commit/d0057d828c9107dc21851725806036e37ff1613c#diff-2559ace193082825164e2976f17866d885f401822b310a9a3b0ccdfe069cb291L27-L38)

**Comment by VerstreuteSeele** [comment]
I am sure, yeah. And the line you linked only shows a message sent in discord. I never come that far as the bot just exits after sending the provied error. And yes, I am sure im using the newest version as I downloaded it directly from here only a few hrs ago

**Comment by DaNeubi** [comment]
Are you trying to set the character via the configuration file?

The configuration file is getting obsolete.
Configuration settings are getting transfered to the database.
Thus, if you want to get another prefix, you need to execute the command `/changeprefix`

I intentionally didn't support the configuration file.
