### ISSUE TITLE
Unable to remove warned users from DB if they have left the server

### ISSUE THREAD

**Issue by CptCryptoVIP3P** [Sahnee-DE/sahnee-bot#41]
If a warned user leaves the Discord server they cannot be unwarned or otherwise removed from the DB.

**Comment by DaNeubi** [comment]
Thanks for this idea.
We will implement this in our new version of the bot. Currently we are not sure how to offer this to the server admins.
I will let you know if we decided how to do.

**Comment by DaNeubi** [comment]
@CptCryptoVIP3P we will provide a Select Menu where you can select the users that are in the database but not in your guild anymore, that will be removed.

**Comment by DaNeubi** [comment]
feature has been fully implemented. will be shipped with 1.0
