### ISSUE TITLE
Shorter aliases for long commands

### ISSUE THREAD

**Issue by CptCryptoVIP3P** [Sahnee-DE/sahnee-bot#43]
/wlb = warnleaderboard
etc...

**Comment by DaNeubi** [comment]
We are currently switching from the old command system to the new / ('slash') command system.
this will make it a whole lot easier for you to execute longer commands.
Furthermore will it allow you and others to easily make changes to the bot per server.

I can happily announce, that we are releasing version 1.0 of the bot.
For now I will close your Issue, as it is solved by our version 1.0 bot.
